### ISSUE TITLE
Clean-up of path "/mnt/local-storage/" needs to be done by LSO after Local volume is deleted

### ISSUE THREAD

**Issue by akgunjal** [openshift/local-storage-operator#125]
I am trying to create local volume using LSO in OCP 4.3 cluster. I have a local SSD disk (`/dev/sdc`) on my node. I created 2 partitions on that disk named `/dev/sdc1` and `/dev/sdc2`. I need to use sdc1 with `volumeMode: Filesystem` and sdc2 with `volumeMode: Block`. Pasting the yaml files for reference. I see the file mode works fine. But block mode creates local volume even for sdc1 device while I have specified only sdc2 in the yaml.

**Local Block volume:**
```
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-block
  namespace: local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: In
          values:
          - worker
  storageClassDevices:
    - storageClassName: localblock
      volumeMode: Block
      devicePaths:
        - /dev/sdc2
```

**Local File volume:**
```
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-file
  namespace: local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: In
          values:
          - ""
  storageClassDevices:
    - storageClassName: localfile
      fsType: ext4
      volumeMode: Filesystem
      devicePaths:
        - /dev/sdc1
```
