### ISSUE TITLE
local-must-gather image not available?

### ISSUE THREAD

**Issue by zmc** [openshift/local-storage-operator#178]
On OCP 4.6.1, I'm trying to debug an issue with the operator, and I can't get local-must-gather working.

From the pod created by `oc adm must-gather --image=quay.io/openshift/local-must-gather:latest`:
```
    state:
      waiting:
        message: 'rpc error: code = Unknown desc = Error reading manifest latest in
          quay.io/openshift/local-must-gather: unauthorized: access to the requested
          resource is not authorized'
        reason: ErrImagePull
```

At first I thought this might be because I'm on a ppc64le cluster, but I can't find the image among the 287 listed at https://quay.io/organization/openshift .
