### ISSUE TITLE
Warning `/dev/disk/by-id/scsi-...-scsi2 was defined in devicePaths, but expected a path in /dev/` since update to `4.9.0-202211280956`

### ISSUE THREAD

**Issue by bo0ts** [openshift/local-storage-operator#385]
Since updating to `4.9.0-202211280956` we see the following warning events:

```
Generated from localvolume-symlink-controller
w02 - /dev/disk/by-id/scsi-...-scsi2 was defined in devicePaths, but expected a path in /dev/
```

The warning does not make sense to me since this is clearly a path in `/dev/`. Here is the relevant localvolume:

```
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  creationTimestamp: "2021-08-18T13:26:48Z"
  finalizers:
  - storage.openshift.com/local-volume-protection
  generation: 1
  name: my-local-storage
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - w02
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-id/scsi-...-scsi2
    fsType: xfs
    storageClassName: my-local-storage
    volumeMode: Filesystem
status:
  conditions:
  - lastTransitionTime: "2022-01-22T18:02:47Z"
    message: Ready
    status: "True"
    type: Available
  generations:
  - group: apps
    lastGeneration: 21
    name: diskmaker-manager
    namespace: openshift-local-storage
    resource: DaemonSet
  managementState: Managed
  observedGeneration: 1
  readyReplicas: 0
```
